### ISSUE TITLE
Request fail

### ISSUE THREAD

**Issue by heldr** [colorhook/node-smushit#1]
``` javascript
httpRequest.write(postData.builder, "binary"); 
```

It has returned false for all requests

**Comment by colorhook** [comment]
I can't understand the issue you met, can you give more details?

**Comment by heldr** [comment]
Sorry! When I run smushit.smushit(path) the post request always return fail

**Comment by colorhook** [comment]
yes, this function return nothing. 
Do you want using smushit's Lower API in your program? I have not return anything or provide a callback in the API. maybe the current version hasn't meet your need at present.

your can install node-smushit globally by npm using the following command: 

``` shell
npm install node-smushit -g
```

then you can smash images in the terminal in a Command Line Interactive manner:

> smushit icon.png

or all images in a directory

> smushit webproject/images/

**Comment by colorhook** [comment]
After learn grunt a little, I know how to make it to work. Next week I will add a callback to the `smushit` API, and the grunt plugin should be asynchronous.

**Comment by heldr** [comment]
Perfect, thanks!

**Comment by colorhook** [comment]
@heldr I had commited node-smushit v0.2.0, please update your code like this to make your grunt plugin work:

``` javascript
var done = this.async();
if(typeof files !== 'string') {
     files = grunt.file.expandFiles( files );
}

if(files.length) {
  smushit.smushit(files, {
    onComplete: function(reports){
        done();
        }
   });
} else {
    grunt.fail.fatal('Image not found, please check if you put the right path.');
}
```

**Comment by heldr** [comment]
No more problems, Thanks a lot!
